name: Recovery Build

on:
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-22.04 # Or your preferred runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build TWRP
        shell: bash
        run: |
          cd twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_creek-trunk_staging-eng
          mka recoveryimage -j4
