    steps:
      - name: Build TWRP
        shell: bash
        run: |
          cd twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_creek-trunk_staging-eng
          mka recoveryimage -j$(nproc --all)
