name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync and Build
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install repo -y
          mkdir -p twrp && cd twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

          mkdir -p device/xiaomi/creek
          cp -av $GITHUB_WORKSPACE/[!t]* device/xiaomi/creek/

          cat <<EOF > device/xiaomi/creek/twrp_creek.mk
          \$(call inherit-product, \$(SRC_TARGET_DIR)/product/core_64_bit.mk)
          \$(call inherit-product, \$(SRC_TARGET_DIR)/product/full_base_telephony.mk)
          \$(call inherit-product, device/xiaomi/creek/device.mk)
          \$(call inherit-product, vendor/twrp/config/common.mk)
          PRODUCT_DEVICE := creek
          PRODUCT_NAME := twrp_creek
          PRODUCT_BRAND := Xiaomi
          PRODUCT_MODEL := POCO M7
          PRODUCT_MANUFACTURER := xiaomi
          EOF

          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_creek-ap2a-eng
          mka recoveryimage -j4
